config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :things do
    member do
      post :create_comment
      get :next_comments
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :thing
  belongs_to :user
end

app/models/thing.rb
class Thing < ActiveRecord::Base
  has_many :comments
  scope :latest, -> { order(created_at: :desc).limit(9) }
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @thing = Thing.find(params[:thing_id])
    form Comment::Create
  end

  def create
    run Comment::Create do |op|
      flash[:notice] = "Created comment for \"#{op.thing.name}\""

      return redirect_to thing_path(op.thing)
    end

    @thing = Thing.find(params[:thing_id])
    render :new
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/things_controller.rb
# frozen_string_literal: true
class ThingsController < ApplicationController
  def index
    @things = Thing.page(params[:page] || 1).per(10)
  end

  def show
    @thing_op = present Thing::Update
    @thing = @thing_op.model

    form Comment::Create, params: params.merge(thing_id: @thing.id)
  end

  def new
    form Thing::Create
  end

  def edit
    form Thing::Update

    render action: :new
  end

  def create
    run Thing::Create do |op|
      return redirect_to op.model
    end

    render action: :new
  end

  def update
    run Thing::Update do |op|
      return redirect_to op.model
    end

    render :new
  end

  def create_comment
    @thing_op = present Thing::Update
    @thing = @thing_op.model

    run Comment::Create, params: params.merge(thing_id: params[:id]) do |op|
      return redirect_to thing_path(op.thing)
    end

    render :show
  end

  def next_comments
    present Thing::Update

    render js: 
      concept('comment/cell/grid', @model, page: params[:page]).call(:append)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_footer.slim
footer
  .row
    .medium-6.columns
      ul.menu
        li
          a href='#'  Legal
        li
          a href='#'  Partner
        li
          a href='#'  Explore
    .medium-6.columns
      ul.menu.float-right
        li.menu-text Copyright

app/views/application/_navigation.slim
.title-bar data-hide-for='small' data-responsive-toggle='realEstateMenu'
  button.menu-icon data-toggle='' type='button'
  .title-bar-title Menu
#realEstateMenu.top-bar
  .top-bar-left
    ul.menu data-responsive-menu='accordion'
      li.menu-text GemGem
      li
        a href="#"  One
      li
        a href="#"  Two
      li
        a href="#"  Three
  .top-bar-right
    ul.menu
      li
        a href="#"  My Account
      li
        a.button Login

app/views/application/_slider.slim
.row
  .medium-7.large-6.columns
    h1 Close Your Eyes and Open Your Mind
    p.subheader There is beauty in space, and it is orderly. There is no
    weather, and there is regularity. It is predictable. Everything in space
    obeys the laws of physics. If you know these laws, and obey them, space
    will treat you kindly.
    button.button Take a Tour
    button.button Start a free trial
  .show-for-large.large-3.columns
    img src='http://placehold.it/400x370&text=PSR1257 + 12 C' /
  .medium-5.large-3.columns
    .callout.secondary
      form
        .row
          .small-12.columns
            label
              | Find Your Dream Planet
              input placeholder='Search destinations' type='text' /
          .small-12.columns
            label
              | Number of Moons
              input placeholder='Moons required' type='number' /
            button.button type='submit'  Search Now!
.row.column
  hr/
.row.column
  p.lead Trending Planetary Destinations

app/views/comments/new.slim
= simple_form_for [@thing, @form] do |f|
  = f.input :body
  = f.collection_radio_buttons :weight, *@form.weights
  = f.fields_for :user do |u|
    = u.input :email

  = f.submit class: 'button'

app/views/home/index.slim
h3 Welcome to GemGem
.row
  = concept('thing/cell/grid').call

app/views/layouts/application.slim
doctype html
html[lang='en']
  head
    meta[charset='utf-8']
    meta[name='viewport' content='width=device-width, initial-scale=1.0']
    title
      = content_for?(:title) ? yield(:title) : 'GemGem'
    = stylesheet_link_tag    'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  body
    = render 'navigation'
    / = render 'slider'
    .row.small-up-1.medium-up-2.large-up-3
        = yield
    / = render 'footer'

app/views/things/_form.slim
= simple_form_for @form do |f|
  = f.input :name, readonly: @form.readonly?(:name)
  = f.input :description

  = f.submit class: 'button'

app/views/things/index.slim
ul
  - @things.each do |t|
    li= t.name

= paginate @things

app/views/things/new.slim
h1 New Thing
= render 'form'

app/views/things/show.slim
.header
  h3
    | #{@thing.name}
    = link_to 'Edit', edit_thing_path(@thing)

= @thing.description

= simple_form_for @form, url: create_comment_thing_path(@thing) do |f|
  = f.input :body
  = f.collection_radio_buttons :weight, *@form.weights

  = f.fields_for :user do |u|
    = u.input :email

  = f.submit class: 'button'

= concept('comment/cell/grid', @thing).call